# Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import math 
import os
import glob

# Loading the Data

In [ ]:
data = pd.read_csv('alldata.csv', header=None)

In [ ]:
data.shape

(1023, 31)

In [ ]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [ ]:
y

0       1
1       1
2       1
3       1
4       1
       ..
1018    0
1019    0
1020    0
1021    0
1022    0
Name: 30, Length: 1023, dtype: int64

# splitting the test and train data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


#Scaling features and target 
X_train = sc_X.fit_transform(X_train)
y_train = le.fit_transform(y_train)

#Transform test set
X_test = sc_X.transform(X_test)
y_test = le.transform(y_test)

## SVM 

In [ ]:
#Initlializing model
from sklearn.svm import SVC # non-linear
classifier = SVC() 


from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'C':[0.25, 0.5, 0.75, 1], 'kernel':['rbf','linear', 'poly', 'sigmoid'], 'gamma':['scale', 'auto']}]

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method accuracy
                           cv=5,         #five sets for cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)

In [ ]:
from sklearn.svm import SVC # non-linear
classifier = SVC(kernel='rbf', C=0.75, gamma='scale') 
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
print("Accuracy", accuracy_score(y_test, y_pred))
print("Test:     ", y_test)
print("Predicted:", y_pred)

from sklearn.metrics import recall_score
print("Recall", recall_score(y_test, y_pred, pos_label=1, average='binary'))
from sklearn.metrics import precision_score
print("Precision", precision_score(y_test, y_pred, pos_label=1,  average='binary'))

Confusion Matrix:
 [[  2  84]
 [  2 117]]
Accuracy 0.5804878048780487
Test:      [1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0
 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1
 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0
 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1]
Predicted: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1]
Recall 0.9831932773109243
Precision 0.582089552238806


## Random Forest

In [ ]:
#Initlializing model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()


from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'n_estimators':[100, 150, 250, 300, 350, 400, 450], 'criterion':['gini', 'entropy', 'log_loss']}]

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method will be acuuracy
                           cv=5,         #five sets for cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)

Best Accuracy: 74.81 %
Best Parameters: {'criterion': 'gini', 'n_estimators': 100}


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(criterion='gini', n_estimators=100)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall ", recall_score(y_test, y_pred, pos_label=1, average='binary'))
print("Precision ", precision_score(y_test, y_pred,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)

Confusion Matrix:
 [[ 41  45]
 [ 11 108]]
Accuracy 0.7268292682926829
Recall  0.907563025210084
Precision  0.7058823529411765
Test:      [1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0
 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1
 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0
 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1]
Predicted: [1 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 1
 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1
 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 1 1
 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1
 0 0 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1]


## Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)

Confusion Matrix:
 [[ 16  70]
 [ 18 101]]
Accuracy 0.5707317073170731
Recall 0.18604651162790697
Precision 0.47058823529411764
Test:      [1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0
 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1
 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0
 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1]
Predicted: [1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1
 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1]


## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()

from sklearn.model_selection import GridSearchCV

#Initializing different parameters that will be used in grid search 
parameters = [{'n_neighbors':[3,5,7,9,11,13,15], 'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']}]

grid_search = GridSearchCV(estimator=classifier, 
                           param_grid=parameters,
                           scoring='accuracy',  #scoring method will be accuracy
                           cv=5,         #cross validation
                           n_jobs=-1)     #n_jobs=-1 will use all the available processors

#Fitting it on train set
grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:",best_parameters)

Best Accuracy: 57.58 %
Best Parameters: {'algorithm': 'auto', 'n_neighbors': 3}


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3, algorithm='auto')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)


cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=0, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=0,  average='binary'))

print("Recall for Non dyslexic:", recall_score(y_test, y_pred, pos_label=1, average='binary'))

print("Precision for Non dyslexic:", precision_score(y_test, y_pred, pos_label=1,  average='binary'))

print("Test:     ", y_test)
print("Predicted:", y_pred)


Confusion Matrix:
 [[28 58]
 [28 91]]
Accuracy 0.5804878048780487
Recall 0.32558139534883723
Precision 0.5
Recall for Non dyslexic: 0.7647058823529411
Precision for Non dyslexic: 0.610738255033557
Test:      [1 1 0 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0
 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0
 0 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1
 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 0
 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1]
Predicted: [0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1
 1 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 0
 0 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0

In [ ]:
import tensorflow as tf

ann = tf.keras.models.Sequential()
#ann.add(tf.keras.layers.Dense(units=50, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=5, activation = 'relu')) 
ann.add(tf.keras.layers.Dense(units=3, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=1024, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=1024, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=475, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=475, activation = 'relu')) 
ann.add(tf.keras.layers.Dense(units=3, activation = 'relu')) 
#ann.add(tf.keras.layers.Dense(units=8, activation = 'relu'))
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy']) 
ann.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
82/82 [==============================] - 0s 678us/step - loss: 0.7072 - accuracy: 0.5697
Epoch 2/100
82/82 [==============================] - 0s 699us/step - loss: 0.6995 - accuracy: 0.5990
Epoch 3/100
82/82 [==============================] - 0s 682us/step - loss: 0.6927 - accuracy: 0.6002
Epoch 4/100
82/82 [==============================] - 0s 651us/step - loss: 0.6871 - accuracy: 0.6051
Epoch 5/100
82/82 [==============================] - 0s 684us/step - loss: 0.6828 - accuracy: 0.6051
Epoch 6/100
82/82 [==============================] - 0s 696us/step - loss: 0.6788 - accuracy: 0.6039
Epoch 7/100
82/82 [==============================] - 0s 676us/step - loss: 0.6759 - accuracy: 0.6027
Epoch 8/100
82/82 [==============================] - 0s 708us/step - loss: 0.6732 - accuracy: 0.6027
Epoch 9/100
82/82 [==============================] - 0s 682us/step - loss: 0.6709 - accuracy: 0.6027
Epoch 10/100
82/82 [==============================] - 0s 650us/step - loss: 0.6692 - accura

82/82 [==============================] - 0s 639us/step - loss: 0.5990 - accuracy: 0.6650
Epoch 82/100
82/82 [==============================] - 0s 650us/step - loss: 0.5983 - accuracy: 0.6626
Epoch 83/100
82/82 [==============================] - 0s 634us/step - loss: 0.5977 - accuracy: 0.6614
Epoch 84/100
82/82 [==============================] - 0s 633us/step - loss: 0.5975 - accuracy: 0.6638
Epoch 85/100
82/82 [==============================] - 0s 640us/step - loss: 0.5965 - accuracy: 0.6626
Epoch 86/100
82/82 [==============================] - 0s 615us/step - loss: 0.5959 - accuracy: 0.6699
Epoch 87/100
82/82 [==============================] - 0s 642us/step - loss: 0.5955 - accuracy: 0.6687
Epoch 88/100
82/82 [==============================] - 0s 633us/step - loss: 0.5947 - accuracy: 0.6760
Epoch 89/100
82/82 [==============================] - 0s 613us/step - loss: 0.5947 - accuracy: 0.6736
Epoch 90/100
82/82 [==============================] - 0s 630us/step - loss: 0.5937 - accuracy: 

In [ ]:
y_pred = ann.predict(X_test)
print(y_pred)
y_pred = (y_pred > 0.9)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1)) #used reshape to print vertically

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

print("Accuracy", accuracy_score(y_test, y_pred))

print("Recall", recall_score(y_test, y_pred, pos_label=1, average='binary'))

print("Precision", precision_score(y_test, y_pred, pos_label=1,  average='binary'))

7/7 [==============================] - 0s 777us/step
[[0.8077032 ]
 [0.6952673 ]
 [0.50684017]
 [0.7363948 ]
 [0.6882054 ]
 [0.48348758]
 [0.7074843 ]
 [0.45947737]
 [0.57451415]
 [0.50684017]
 [0.81008774]
 [0.50684017]
 [0.735671  ]
 [0.43731803]
 [0.50684017]
 [0.6738617 ]
 [0.6988024 ]
 [0.64617634]
 [0.48660505]
 [0.6528033 ]
 [0.6445096 ]
 [0.70006716]
 [0.50684017]
 [0.6964738 ]
 [0.728823  ]
 [0.47514334]
 [0.70555824]
 [0.6952673 ]
 [0.50684017]
 [0.48677096]
 [0.6952673 ]
 [0.7115991 ]
 [0.59531224]
 [0.6952673 ]
 [0.50684017]
 [0.56314087]
 [0.6946469 ]
 [0.6952673 ]
 [0.7310371 ]
 [0.50684017]
 [0.55375564]
 [0.4037719 ]
 [0.5431387 ]
 [0.6571834 ]
 [0.6952673 ]
 [0.49441198]
 [0.6952673 ]
 [0.47919175]
 [0.75432235]
 [0.6099343 ]
 [0.7126796 ]
 [0.5832602 ]
 [0.73313504]
 [0.49078932]
 [0.6952673 ]
 [0.7010431 ]
 [0.4616346 ]
 [0.4089528 ]
 [0.6644103 ]
 [0.70515424]
 [0.6952673 ]
 [0.7734013 ]
 [0.7881098 ]
 [0.50684017]
 [0.62497985]
 [0.6386456 ]
 [0.64565855]
 [0.88000